services:
  - type: web
    name: kokoro-playht-stream
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
    plan: free
